export const SET_METEO_DATA = 'SET_METEO_DATA';
export const FETCH_METEO_DATA_FAILED = 'FETCH_METEO_DATA_FAILED';

export const SET_YEAR_DATA = 'SET_YEAR_DATA';
export const FETCH_YEAR_DATA_FAILED = 'FETCH_YEAR_DATA_FAILED';

export const SET_MONTH_DATA = 'SET_MONTH_DATA';
export const FETCH_MONTH_DATA_FAILED = 'FETCH_MONTH_DATA_FAILED';

export const SET_DAY_DATA = 'SET_DAY_DATA';
export const FETCH_DAY_DATA_FAILED = 'FETCH_DAY_DATA_FAILED';

export const SET_SONOFF_DATA = 'SET_SONOFF_DATA';
export const FETCH_SONOFF_DATA_FAILED = 'FETCH_SONOFF_DATA_FAILED';
export const SEND_SONOFF_DATA_FAILED = 'SEND_SONOFF_DATA_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
